"""One-time script: add summary fields to all GEC-13 chapter JSON files."""
import json
import os

SUMMARIES = {
    'chapter01': {
        '1.0': 'GEC-13 covers ground modification technologies for improving soil and rock engineering properties for transportation infrastructure. Methods range from ancient techniques (straw-reinforced bricks, timber piles) to modern engineered systems (deep soil mixing, CMC, geosynthetics). FHWA published GEC-13 to standardize practice across transportation agencies.',
        '1.1': 'Ground modification improves soil or rock to allow construction that would otherwise be infeasible or too costly. The modified ground may serve as a foundation, retaining structure, embankment, or slope. Improvement occurs through densification, consolidation acceleration, reinforcement, cementation/mixing, or grouting.',
        '1.2': 'Ground modification history spans thousands of years: straw-reinforced earthen bricks in ancient Mesopotamia and timber corduroy roads in Roman construction. Modern practice began in the 1930s with vibratory compaction in Germany and preloading with vertical drains in Sweden, expanding through the 1960s-1980s to include deep mixing, grouting, and geosynthetics.',
        '1.3': 'Volume I covers five categories most common in transportation: vertical drains/accelerated consolidation, lightweight fills, deep compaction, aggregate columns, and column-supported embankments. Volume II covers deep mixing, grouting, soil nailing, micropiles, and geosynthetic reinforcement. Each chapter covers description, feasibility, design, construction, specs, and case histories.',
        '2.0': 'Ground modification technologies serve six basic functions: (1) increase bearing capacity, (2) reduce settlement, (3) increase shear strength for stability, (4) reduce lateral earth pressures, (5) accelerate consolidation, and (6) mitigate liquefaction and contaminant migration. Multiple functions may be achieved simultaneously by a single technology.',
        '2.1': 'Table 1-1 classifies technologies by primary function and applicable soil types. Densification (DDC, vibro-compaction) is primarily effective in granular soils with <15% fines. Consolidation methods (preloading, PVDs) address soft cohesive soils. Reinforcement and grouting technologies apply across a broad range of soil types and conditions.',
        '2.2': 'Each technology has applicability limits defined by soil type, treatment depth, groundwater conditions, proximity to structures, and environmental constraints. Table 1-2 summarizes limits for major technology categories. DDC is generally limited to ~10 m depth in granular soils; jet grouting can treat most soils but requires careful pressure control near structures.',
        '2.3': 'Feasibility evaluation is a preliminary assessment to determine which technologies are viable for a given project. Considers subsurface conditions, project requirements (loading, settlement tolerance, schedule), site constraints (access, proximity to structures, environmental restrictions), and cost. A three-step process screens technologies from a broad list to a short list for detailed evaluation.',
        '3.0': 'Ground modification technologies can be classified by function, construction method, applicable soil type, or improvement mechanism. GEC-13 uses a dual framework: functional classification (what is accomplished) and construction method classification (how it is installed). The two classifications together guide initial technology screening.',
        '3.1': 'Table 1-3 organizes technologies by engineering purpose: earthwork construction (compacted fills, lightweight fills, excavation), densification (DDC, vibro-compaction, blast, RIC), consolidation (preloading, PVDs), reinforcement and mixing (stone columns, DM, micropiles, soil nails, geosynthetics), and grouting (permeation, compaction, jet).',
        '3.2': 'Area treatment methods (DDC, vibro-compaction, preloading) improve a volume of soil without creating discrete elements. Columnar inclusion methods (stone columns, DM columns, CMC) create discrete stiffer elements. Reinforcement layers (geosynthetics, soil nails) provide tensile resistance within the soil mass. Each category uses different monitoring and QA approaches.',
        '4.0': 'Ground modification projects involve risks from subsurface variability, construction process control, and performance verification. Key constraints include vibration and noise limits near structures, environmental restrictions on materials and waste, ROW limitations, and schedule requirements. Risk management should use observational methods with contingency plans.',
        '5.0': 'Contracts may use prescriptive (method-based) or performance-based specifications, or a combination. Prescriptive specs define installation parameters (grid spacing, energy per drop, withdrawal rate). Performance specs define required outcomes (minimum SPT N, maximum settlement, minimum qu). Performance specs give contractors flexibility but require more rigorous QA/QC and post-treatment verification.',
        '6.0': 'Table 1-6 provides comparative unit costs for ground modification technologies as of 2016. Cost analysis should compare total installed cost of ground modification plus the supported structure against conventional alternatives (deep foundations, realignment, bridging). Regional variation, site access, treatment volume, and mobilization costs significantly affect overall economics.',
        '7.0': 'GeoTechTools (www.geotechtools.org) is a web-based technology selection resource from SHRP2 Project R02 with FHWA collaboration. Provides catalog of 50+ technologies with technical summaries, case histories, design guidance, and a systematic selection tool that screens technologies based on soil type, depth, project type, and constraints.',
        '8.0': 'GEC-13 presents a 12-step process: (1) identify project requirements; (2) characterize subsurface conditions; (3) identify problematic conditions; (4) identify applicable technologies; (5) conduct preliminary feasibility evaluation; (6) identify site constraints; (7) screen technologies; (8) evaluate costs; (9) select technology; (10) design; (11) specify; (12) perform QA/QC during construction.',
        '9.0': 'Chapter 1 references include FHWA ground improvement manuals (Elias et al. 2006; Schaefer et al. 2017), AASHTO LRFD Bridge Design Specifications (2014), ground improvement textbooks (Moseley & Kirsch 2004; Chu et al. 2009), and SHRP2 R02 GeoTechTools documentation.',
    },
    'chapter02': {
        '2.1.0': 'Prefabricated vertical drains (PVDs) reduce the drainage path in thick compressible clay from the full layer thickness to half the drain spacing, reducing consolidation time from decades to months. Modern PVDs consist of a plastic core wrapped in geotextile filter fabric, typically 100 mm wide x 4 mm thick. Drain spacing of 1.0-3.0 m is typical in triangular or square patterns.',
        '2.2.0': 'PVDs are most effective in normally to lightly overconsolidated soft clays and silts with consolidation coefficient c_v of 0.5-10 m²/year. Table 2-1 summarizes typical PVD transportation applications. Not effective in highly organic soils where secondary compression dominates, highly sensitive soils prone to remolding during installation, or very stiff/hard soils where consolidation is not the governing concern.',
        '2.3.0': 'PVD installation uses a steel mandrel (typically 60 mm × 120 mm rectangular or rhombic cross-section) pushed or vibrated to target depth, with the PVD threaded through the mandrel. An anchor plate prevents the PVD from being pulled back during mandrel withdrawal. Installation rates of 300-700 m/hour are typical. Mandrel size and shape are critical: larger mandrels cause more smear zone disturbance.',
        '2.4.0': 'Vertical drain system design combines Terzaghi (1943) one-dimensional vertical consolidation with Barron/Hansbo (1948/1981) radial consolidation theory. The overall degree of consolidation U is computed by combining vertical and radial components: 1-U = (1-U_v)(1-U_r). The combined equation allows calculation of the time required to reach a target degree of consolidation for a given drain spacing.',
        '2.4.1': 'Barron (1948) developed radial consolidation theory for a cylindrical unit cell. For ideal conditions (no smear, no well resistance), F(n) = ln(n) - 3/4, where n = d_e/d_w (equivalent zone diameter / drain diameter). Hansbo (1981) extended the theory to incorporate smear effects and well resistance, adding terms F(s) and F(r) to the denominator of T_h in the U_r equation.',
        '2.4.2': 'Drain spacing is determined iteratively: assume spacing, compute combined degree of consolidation U at the end of available construction time, adjust until U reaches target (typically 90-95%). Equivalent influence zone diameter: d_e = 1.128×S for square patterns, d_e = 1.050×S for triangular. The mandrel equivalent diameter d_m = sqrt(4×a×b/π) for a rectangular mandrel of dimensions a x b.',
        '2.4.3': 'The mandrel disturbs soil around the drain, creating a smear zone with reduced horizontal permeability. Smear zone diameter d_s ranges from 2-5 times the mandrel equivalent diameter; permeability ratio k_h/k_s = 1.5-4.0 is typical. Smear zone significantly increases drain spacing required to achieve a target consolidation in a given time, making mandrel size selection a key design decision.',
        '2.5.0': 'PVD specifications require: minimum discharge capacity q_w ≥ 100 m³/year per meter of drain at 350 kPa lateral pressure; AOS of filter < D85 of surrounding soil; tensile strength; resistance to clogging. Installation specifications control mandrel penetration rate, drain spacing tolerance (typically ±75 mm), drain length, and trimming at the granular drainage blanket.',
        '2.6.0': 'The I-95/Route 1 interchange in New Jersey treated 6-15 m of soft organic clay with PVDs at 1.5 m triangular spacing plus 4.5 m surcharge fill, achieving 90% consolidation in 8 months vs. 15-20 years without drains. The Port of Brisbane expansion used PVDs with vacuum preloading at 1.0 m spacing to achieve 95% consolidation of 30 m of soft marine clay within 12 months before container terminal construction.',
    },
    'chapter03': {
        '3.1.0': 'Lightweight fill materials (unit weight 1-12 kN/m³) replace conventional fill (18-22 kN/m³) to reduce stress on compressible foundation soils, improving stability and reducing settlement. Four main types: EPS geofoam (0.12-0.32 kN/m³), foamed concrete (3-8 kN/m³), shredded tires (6-8 kN/m³), and granular lightweight fills (pumice, expanded shale, wood fiber: 5-15 kN/m³). Table 3-1 summarizes material properties.',
        '3.2.0': 'EPS geofoam (0.12-0.32 kN/m³) is the lightest fill for transportation applications. Factory-manufactured blocks in standard sizes (typically 610×1220×2440 mm) are placed in stacked courses. Design compressive resistance per ASTM D6817 (EPS15 through EPS100 by density). Buoyancy, fire protection, and differential settlement between blocks are key design concerns.',
        '3.3.0': 'Foamed concrete (cellular concrete) is a cementitious lightweight fill with unit weight 3-8 kN/m³, produced by introducing preformed foam into a cement-water slurry. Mixed at a batch plant and pumped as flowable fill. Unconfined compressive strength 350-3,500 kPa depending on density and mix design. Self-leveling, can be placed in restricted access areas, and may be re-excavated with standard equipment.',
        '3.4.0': 'Granular lightweight fills (5-15 kN/m³) include wood fiber (6-10 kN/m³, susceptible to biodegradation and combustion), shredded tires (6-8 kN/m³, potential leachate concerns), expanded shale/clay/slate (ESCS, 8-12 kN/m³, durable), and fly ash (12-15 kN/m³). Placed and compacted with conventional earthwork equipment. Each has specific durability and environmental considerations.',
        '3.5.0': 'Design evaluates global stability, settlement, bearing capacity, and interface behavior. Primary objective: reduce applied stress at foundation surface to meet settlement and stability requirements. Net stress increase = unit weight of lightweight fill × fill height. EPS design must check: buoyancy (if below GWT), differential settlement between blocks, and interface friction with adjacent structures.',
        '3.6.0': 'EPS specifications reference ASTM D6817 for material classification; compressive resistance per ASTM D1621; density testing; dimensional tolerance verification for each block. Foamed concrete: mix design testing for target unit weight and compressive strength, flow testing, and field sampling. Granular lightweight fills: gradation, compaction, and degradation testing per appropriate ASTM standards.',
        '3.7.0': 'Route 23 (Wayne, NJ, 2001): 26,500 m³ of EPS blocks for 1.2 km embankment widening over 10-15 m of soft organic clay, reducing settlement from ~600 mm to <50 mm. I-15 Reconstruction (Salt Lake City, UT, 2001): EPS blocks reduced lateral pressure on abutments. I-90 (Snoqualmie Pass, WA): EPS blocks used under highway embankment in area susceptible to thermal frost heave.',
    },
    'chapter04': {
        '4.1.0': 'Deep dynamic compaction (DDC) densifies loose granular soils and partially saturated fills by repeatedly dropping heavy tampers (5-40 tonnes) from heights of 10-40 m using cranes. Developed by Menard in France in the 1960s. Applied in grids with tamper prints at 2-5 m spacing; multiple passes at decreasing energy (high energy for depth, ironing pass for surface). Not effective in saturated fine-grained soils.',
        '4.1.1': 'DDC is most effective in freely draining granular soils with <15% fines. Effectiveness decreases significantly above 15% fines; not recommended for saturated clays or silts. DDC can treat loose fills, collapsible soils, sinkholes, and karst. Vibration monitoring required near existing structures; typical exclusion zone 20-50 m from sensitive structures.',
        '4.1.2': 'Maximum depth of improvement: D = n × sqrt(W × H), where D = depth (m), W = tamper weight (tonnes), H = drop height (m), n = empirical coefficient (0.3-0.8, typically 0.5 for initial estimates). The equation is empirical and should be calibrated to site conditions. Effective treatment zone is typically 0.5 to 0.7 × D_max. Table 4-1 provides n values by soil type.',
        '4.1.3': 'DDC design selects tamper weight, drop height, grid spacing, number of drops per print, number of passes, and time between passes. Process: (1) estimate depth using D = n×sqrt(W×H); (2) select W and H; (3) design grid spacing (typically 1.5-2.0 × D_max); (4) specify number of drops per print (stop when crater depth <0.2 m per blow or surface heave occurs); (5) apply ironing pass for upper 1-2 m.',
        '4.2.0': 'Vibro-compaction (vibroflotation) densifies granular soils by inserting a 300-500 mm diameter vibrating probe (vibroflot) and using horizontal vibrations to rearrange soil particles into a denser state. The vibroflot generates centrifugal force of 150-400 kN at 20-60 Hz, causing liquefaction and densification around the probe. Backfill (coarse sand or gravel) is added from the surface as the vibroflot withdraws.',
        '4.2.1': 'Brown (1977) suitability number SN quantifies treatability from grain size: SN = 1.7 × sqrt(3/(D50)² + 1/(D20)² + 1/(D10)²), where D50, D20, D10 are particle diameters in mm. SN < 10: excellent; 10-20: good; 20-30: fair; 30-50: poor; >50: unsuitable. Soil with high fines content (>15%) produces high SN values and is generally unsuitable for vibro-compaction without modification.',
        '4.2.2': 'Probe spacing (1.5-4.0 m, triangular preferred) is the primary design variable. Effective treatment radius per probe is typically 1.0-2.5 m. Design targets post-treatment relative density Dr ≥ 70-80% for liquefaction mitigation, or minimum SPT N60 or CPT qc values. QC uses CPT or SPT before/after treatment; post-treatment verification typically 24-72 hours after installation.',
        '4.3.0': 'DDC case: Trident submarine base (Kings Bay, GA, 1981-1984) treated 500,000 m² of loose hydraulic fill to 7-12 m depth using 15-33 t tampers from 12-30 m, achieving target SPT N > 15 blows/ft. Vibro-compaction case: I-90 interchange (Seattle) treated loose sand fills to 10-12 m depth at 2.5 m triangular spacing, increasing CPT qc from 3-5 MPa to >15 MPa.',
    },
    'chapter05': {
        '5.1.0': 'Stone columns (vibro-replacement) are compacted coarse aggregate inclusions in soft cohesive or loose granular soils that improve bearing capacity, reduce settlement, accelerate consolidation, and mitigate liquefaction. Constructed by vibro-replacement: vibroflot creates a hole, which is backfilled with gravel or crushed stone in lifts. Typical column diameters 450-900 mm at 1.5-3.5 m spacing.',
        '5.1.1': 'Stone columns are most effective in soft to medium stiff cohesive soils with undrained shear strength s_u = 15-50 kPa. Below s_u = 15 kPa, insufficient lateral confinement; alternatives (deep mixing, CMC) should be considered. Not effective in very soft peats or highly organic soils. Suitable for liquefaction mitigation in granular soils through densification and drainage. Treatment depth limited to ~10-15 m with conventional equipment.',
        '5.1.2': 'Area replacement ratio a_s = A_c / A_unit_cell, where A_c = π×d²/4 (column area). Equivalent influence zone diameter: d_e = 1.050×S for triangular pattern, 1.128×S for square pattern. Typical a_s ranges from 0.10 to 0.35. Higher a_s improves settlement reduction and bearing capacity but increases cost. The Priebe (1995) improvement factor n_0 increases with a_s and column friction angle φ_c.',
        '5.1.3': 'Settlement reduction factor n_0: S_improved = S_unimproved / n_0. Depends on area replacement ratio a_s and stress concentration ratio n = σ_c/σ_s (typically 2-5 for stone columns, 5-20 for stiffer CMC). Priebe (1995) basic improvement factor ranges from approximately 1.5 at a_s = 0.10 to 5+ at a_s = 0.35, increasing with column stiffness relative to surrounding soil.',
        '5.2.0': 'Rammed aggregate piers (RAPs, Geopier) are short columnar aggregate inclusions installed by driving a hollow mandrel to design depth, extracting to create a hole, and compacting aggregate in thin lifts (150-300 mm) using a high-energy impact rammer. The ramming densifies aggregate and laterally prestresses surrounding soil. Typical pier diameters 280-380 mm at 1.5-2.5 m spacing. Better performance than vibro-replacement in stiff soils.',
        '5.3.0': 'Priebe (1995) method calculates settlement improvement factor n_0 from cavity expansion theory applied to the unit cell model. The basic improvement factor n_0 is a function of a_s and the coefficient of lateral earth pressure K_c in the column. Improved factor n_1 corrects for column compressibility; n_2 for overburden effects. Design typically verified with settlement monitoring and load testing.',
        '5.3.1': 'Unit cell model: each column and its tributary soil deform under equal vertical strain. Applied stress distributes between column (σ_c) and soil (σ_s) in proportion to their stiffness ratio — the stress concentration ratio n. Compatibility: n × a_s × σ_c + (1-a_s) × σ_s = σ_applied. The stress concentration ratio n governs how much load the column carries vs. the surrounding soil.',
        '5.4.0': 'Stone column construction uses wet top-feed (vibroflot jetted in with water, backfilled from surface) or dry bottom-feed (vibroflot pressed into ground without water, aggregate fed through a pipe inside the vibrating probe). Wet top-feed generates large volumes of spoil; dry bottom-feed produces less spoil and better control. QC: column diameter, depth, aggregate volume, and post-treatment in-situ testing (CPT or SPT).',
        '5.5.0': 'I-78 embankment (NJ): 900 mm diameter stone columns at 2.5 m triangular spacing supported 6 m embankment over 10-15 m of soft marine clay (s_u = 15-30 kPa), meeting settlement limits in 3 months vs. 2+ years without treatment. Liquefaction mitigation: I-5 (Seattle) used vibro-replacement stone columns at 2.0 m spacing to treat 8-12 m of liquefiable sand, increasing post-treatment CPT qc from 4-8 MPa to >12 MPa.',
    },
    'chapter06': {
        '6.1': 'Column-supported embankments (CSE) use vertical foundation elements beneath a load transfer platform (LTP) to support embankments over soft compressible soils, transferring load to competent bearing strata and bypassing weak subgrade. The LTP — typically compacted granular fill with geosynthetic reinforcement — distributes embankment load to column heads via soil arching. Applicable for high embankments where differential settlement or stability prevents conventional approaches.',
        '6.2': 'CSE systems are most appropriate when: soft soil is too deep or weak for aggregate columns or deep mixing; differential settlement between embankment and adjacent structures must be minimized; schedule prohibits preloading; or environmental conditions preclude surcharging or dewatering. Column type selection depends on required capacity, access constraints, vibration sensitivity, and cost.',
        '6.3': 'Three primary design components: (1) column axial and lateral capacity; (2) LTP design to distribute embankment load to column heads; (3) geosynthetic reinforcement design within LTP. Load transfer efficiency (LTE) describes the fraction of embankment load carried by columns. Design methods include Hewlett & Randolph (1988), van Eekelen (2012), Nordic Guidelines, and BS 8006.',
        '6.4': 'Column selection based on soil conditions, required capacity, stiffness, equipment access, and cost. Options: driven piles (timber, concrete, steel); ACIP piles; auger-displacement piles; deep mixed columns; controlled modulus columns (CMC); controlled stiffness columns (CSC). Stiffness must be matched to LTP design: stiffer columns require better LTP arching and geosynthetic reinforcement design.',
        '6.5': 'LTP minimum height: H_LTP ≥ 0.7 × (s - d), where s = center-to-center column spacing, d = column head diameter. Geosynthetic reinforcement placed within LTP carries differential load between column heads by tensile membrane action. Design tension T_max from vertical equilibrium of the arched zone. Multiple geosynthetic layers at different elevations may be used for higher embankments.',
        '6.6': 'Settlement from three sources: (1) LTP granular fill compression (typically small); (2) elastic and long-term creep of columns; (3) differential settlement between column heads and surrounding subgrade. Total surface settlement controlled primarily by column compression since arching transfers most embankment load to columns. Subgrade settlement under reduced stress is typically small.',
        '6.7': 'Construction sequence: (1) site preparation and working platform; (2) column installation; (3) column head caps; (4) LTP granular fill placement and compaction; (5) geosynthetic reinforcement layers; (6) additional LTP fill; (7) embankment fill in lifts. Settlement monitoring instruments (settlement plates, inclinometers, piezometers) typically installed before column construction.',
        '6.8': 'CSE specifications define column type, installation method, minimum length, diameter, design capacity, and acceptance criteria. Acceptance: load testing (static or dynamic) for driven piles; integrity testing (CSL, gamma-gamma, PIT) for drilled elements; core strength testing for DM columns. LTP and geosynthetic reinforcement specifications follow earthwork and geosynthetic standards.',
        '6.9': 'Key references: BS 8006:2010 (British Standard), EBGEO (German Recommendations, 2010), Hewlett & Randolph (1988) arching model, van Eekelen et al. (2012) updated arching models, FHWA GEC-13 Chapter 6. Geosynthetic reinforcement design per FHWA GEC-11.',
    },
    'chapter07': {
        '7.1': 'Deep mixing (DM) mechanically blends in-situ soil with cementitious binders (Portland cement, lime, fly ash, slag, or combinations) to create a stiffer, stronger, lower-permeability treated mass. Two primary methods: dry deep mixing (DDM) injects dry binder through hollow mixing tools; wet deep mixing (WDM) injects binder as slurry. Single-axis tools produce individual columns (0.5-1.0 m diameter); multi-axis tools produce overlapping columns or panels.',
        '7.2': 'Deep mixing is feasible in most fine-grained soils and organic soils that can be blended with binder. Key factors: soil chemistry (highly organic or acidic soils may inhibit cement hydration — minimum pH > 5), maximum depth (typically 20-30 m for conventional equipment), binder compatibility, and equipment access. Design qu from bench-scale mix design testing on site-specific soils; field qu is typically lower than lab qu by a factor of 2-3.',
        '7.3': 'Primary engineering property is unconfined compressive strength qu. Design values: 200-500 kPa for lime-cement in soft Scandinavian clays; 500-1,000 kPa for lime-cement in US soft soils; 1,000-4,000 kPa for WDM cement columns in US practice. Table 7-2 provides typical qu by soil/method. Elastic modulus E ≈ 75-150 × qu. Permeability is typically 10⁻⁷ to 10⁻⁸ cm/s after treatment.',
        '7.4': 'DM columns supporting embankments are designed as stiff columnar inclusions with checks: (1) bearing capacity of individual columns; (2) settlement using unit cell or composite modulus approach; (3) global stability with DM columns replacing weak soil contribution; (4) lateral sliding between column rows. Area replacement ratio a_r = 0.20-0.50 is typical for embankment support.',
        '7.5': 'DM walls and grids are used for excavation support, retaining walls, and liquefaction mitigation. Walls act as gravity retaining structures with checks for overturning, sliding, bearing capacity, and internal shear. Grid and cellular configurations enclose volumes of untreated soil, providing lateral confinement. Liquefaction mitigation: grid or lattice reduces shear strain in enclosed soil and provides drainage.',
        '7.6': 'DDM: hollow-stem auger with injection ports and paddle mixing blades; dry binder injected under low air pressure during withdrawal; multiple passes improve uniformity. WDM: slurry injected under pressure through the tool during penetration and withdrawal; larger equipment with higher energy. Production rates 3-8 m/min for DDM, 1-4 m/min for WDM. Wet mixing produces more uniform results but requires spoil management.',
        '7.7': 'DM specifications define: binder type and minimum content (kg/m³); minimum qu at 28 or 90 days; acceptance criteria for column integrity (typically no more than 20% of cores below minimum qu); and installation parameters. FHWA recommends at least 3 cores per 1,000 linear meters. Pre-production trial columns with coring and testing are recommended.',
        '7.8': 'Key references: FHWA-RD-99-167 (Porbaha et al. 1998) and FHWA-HRT-13-046 (Bruce et al. 2013) for US design practice; EuroSoilStab (2002) Nordic Design Guidelines; Japanese CDM Manual (CDM Association 2008); Kitazume & Terashi (2013) textbook.',
    },
    'chapter08': {
        '8.1': 'Grouting techniques inject cementitious, chemical, or particulate materials into soil or rock to improve strength, reduce permeability, fill voids, or compact loose materials. Major methods for transportation: (1) permeation grouting — displaces pore fluid without disturbing soil fabric; (2) compaction grouting — forms expanding bulb that densifies surrounding soil; (3) jet grouting — erodes and mixes in-situ soil to form soilcrete columns; (4) fracture/compensation grouting; (5) bulk void filling and slabjacking.',
        '8.2': 'Permeation grouting injects low-viscosity grout (sodium silicate, acrylamide, or Portland cement in coarse soils) into soil pores without disturbing soil fabric. Applicable to clean sands and gravels with permeability k > 10⁻³ cm/s. Groutability ratio N = D15_soil / D85_grout > 24 for reliable penetration; N > 11 for limited penetration. Achieves significant strength increase (200-1,000 kPa) and permeability reduction.',
        '8.3': 'Compaction grouting injects very stiff mortar (0-25 mm slump, w/c = 0.3-0.5) through a casing under high pressure, forming a growing bulb that displaces and densifies surrounding soil. Effective in loose to medium dense granular soils where pore pressures can dissipate. Grout bulbs typically 0.2-1.0 m diameter. Applications: densification of loose fills, remediation of subsidence, and lifting of settled structures.',
        '8.4': 'Jet grouting uses high-velocity fluid jets to erode and mix in-situ soil with cementitious grout, forming soilcrete columns. Three systems: single-fluid (grout jet only, 0.4-0.8 m diameter columns), double-fluid (grout + air shroud, 0.8-1.5 m), triple-fluid (water cutting + air shroud + grout injection, 1.0-3.0+ m). Table 8-2 compares system characteristics. Soilcrete qu ranges from 0.5-20 MPa depending on soil type and mix design.',
        '8.5': 'Fracture grouting injects grout at pressures exceeding minor principal stress, creating disc-shaped grout lenses that heave ground or prestress soil mass. Compensation grouting uses sleeve-port (tube-à-manchette) pipes installed in advance to allow controlled injection during tunneling or excavation, counteracting surface settlement at the source.',
        '8.6': 'Bulk void filling addresses large underground voids from karst dissolution, abandoned mine workings, or utility vaults using flowable fill (CLSM), lean concrete, or grout. Void detection via GPR, seismic, or electrical resistivity methods. Slabjacking raises settled concrete slabs by injecting cement-sand slurry or polyurethane foam under pressure through holes drilled through the slab.',
        '8.7': 'Grouting construction requires control of injection pressure, grout volume, and injection sequence. Injection pressure limits established through pre-construction pressure testing. Injection sequence proceeds from outer to inner holes to confine treated zone. QC monitoring: pressure and volume at each hole, surface heave survey. Post-grouting verification with borings, CPT, or geophysical methods.',
        '8.8': 'Key references: FHWA Grouting Reference Manuals (Henn 1996; Byle & Borden 1995); Nonveiller (1989) grouting theory; Raabe & Esters (1990) compaction grouting; Burke (2004) jet grouting; ASCE Geotechnical Special Publications on grouting.',
    },
    'chapter09': {
        '9.1': 'Soil nailing installs passive steel bars (typically 25-44 mm threaded bar) into existing cut slopes at 10-20° below horizontal in arrays of 1.0-2.0 m spacing, then grouted in drilled holes, to create a composite reinforced mass acting as a gravity retaining structure. The nail head connects to a structural shotcrete or CIP concrete wall face. LRFD design follows AASHTO and FHWA GEC-7.',
        '9.2': 'Feasibility requires: temporary stand-up time of at least 1-2 hours at unsupported cut height of 1-2 m; adequate bond between grout and soil (typically 50-300 kPa, varying by soil type). Suitable soils: stiff to hard fine-grained soils, dense granular soils with some cohesion, weathered rock, glacial till, and compacted fills. Not recommended in soft clays (s_u < 25 kPa), clean dry sands below GWT, or aggressive chemical environments without corrosion protection.',
        '9.3': 'Soil nail wall LRFD design checks: (1) external stability — global stability, sliding, overturning, and bearing capacity; (2) internal stability — nail pullout, nail tensile failure, and facing failure; (3) facing design — flexure, punching shear, and connection. AASHTO resistance factor φ_bond = 0.50-0.65 for pullout; φ_T = 0.56 for nail tension. Nail length typically 60-80% of wall height; nail inclination 10-20° below horizontal.',
        '9.4': 'Construction proceeds top-to-bottom in lifts: (1) excavate 1.0-1.5 m lift; (2) drill nail holes at design spacing and inclination; (3) insert nail bars and tremie-grout from bottom up; (4) place bearing plate and nut; (5) apply first shotcrete layer; (6) install drainage elements; (7) apply final shotcrete or CIP facing. Excavation must not exceed stand-up time limits. Drainage layer between shotcrete and soil reduces hydrostatic pressure on facing.',
        '9.5': 'Nail testing per FHWA GEC-7: verification tests (sacrificial nails, minimum 2 per wall, loaded to 200% design load) confirm site-specific bond strength; proof tests (minimum 5% of production nails, loaded to 150% design load) verify individual nail performance. Proof test acceptance: <1 mm permanent displacement at lock-off load after unloading.',
        '9.6': 'Primary design reference: FHWA GEC-7 (Lazarte et al. 2015, FHWA-NHI-14-007). Additional: Elias & Juran (1991); Byrne et al. (1996) soil nail wall construction manual; AASHTO LRFD Section 11.10 (2014).',
    },
    'chapter10': {
        '10.1': 'Micropiles are small-diameter (100-300 mm), drilled and grouted piles resisting axial and lateral loads through skin friction in the bond zone and structural capacity of the steel reinforcement (pipe casing, rebar, or combination). Developed by Lizzi in Italy in the 1950s as pali radice (root piles). Classification per FHWA-NHI-05-039: Type A (gravity-fed grout), Type B (pressure-grouted during withdrawal), Type C/D (postgrouted). Design capacity typically 200-2,000 kN.',
        '10.2': 'Micropiles are feasible in virtually any soil or rock condition; small drilling diameter penetrates cobbles, boulders, and hard rock. Best suited to: (1) underpinning existing foundations where excavation or vibration must be minimized; (2) restricted access (low headroom, tight spaces); (3) complex subsurface conditions unsuitable for other pile types; (4) seismic retrofitting of existing foundations. More expensive per unit capacity than conventional piles but uniquely suited to access-constrained applications.',
        '10.3': 'Design governed by lesser of structural capacity and geotechnical bond capacity. Structural: Q_structural = f_y × A_s + f_grout × A_grout. Bond zone capacity: Q_bond = π × d_b × L_b × α_bond, where d_b = drill hole diameter, L_b = bond zone length, α_bond = unit bond stress (50-600 kPa depending on soil/rock type and grout method per Table 5-3 of FHWA-NHI-05-039). AASHTO LRFD resistance factor φ = 0.50-0.65 for bond.',
        '10.4': 'Drilling methods: rotary duplex (casing and bit advance simultaneously, preferred for difficult soils), down-the-hole (DTH) hammer for rock, or hollow-stem auger for soft soils. Casing left in place above bond zone for Types B, C, D. Tremie grouting from bottom up fills the drill hole. Post-grouting (Types C, D) injects additional grout under pressure through a sleeve-port pipe to increase bond stress by 50-100%.',
        '10.5': 'Load testing follows ASTM D1143 (compression), D3689 (tension), D3966 (lateral). Verification tests (sacrificial piles, minimum 1 per project, loaded to 200% design): confirm design bond stress is achievable. Proof tests (minimum 5% of production micropiles, loaded to 150% design load): verify individual pile performance. Acceptance: <6 mm permanent settlement after unloading for proof tests in most specifications.',
        '10.6': 'Primary reference: FHWA-NHI-05-039 (Sabatini et al. 2005), full LRFD design procedures. Additional: Lizzi (1978) pali radice; Juran et al. (1999) reticulated micropile networks; ADSC/DFI Micropile Committee guidelines.',
    },
    'chapter11': {
        '11.1': 'Geosynthetic reinforcement uses geogrids and woven geotextiles as horizontal tensile reinforcement within compacted soil fills to create reinforced soil structures: MSE walls, reinforced soil slopes (RSS), and reinforced embankments. The geosynthetic transfers tensile load through interface friction and passive resistance. LRFD design follows AASHTO and FHWA GEC-11. Long-term design strength LTDS = T_ult / (RF_ID × RF_CR × RF_CBD).',
        '11.2': 'Geogrids: polymeric grid structures (PET, HDPE, or PP) providing interface friction and passive resistance. PET geogrids have low creep and high stiffness, preferred for MSE walls. HDPE and PP geogrids have higher creep; applied primarily in RSS and embankments. Woven PET geotextiles provide high tensile strength in a filter-compatible format. Material selection considers tensile strength, creep, chemical durability, and installation damage resistance.',
        '11.3': 'Geosynthetic reinforcement in soft ground embankments addresses: (1) bearing capacity failure — geosynthetic increases bearing capacity by preventing lateral spreading; (2) circular slip failure — tensile force reduces driving moment; (3) differential settlement — geosynthetic bridges between firmer and softer zones. Design tension from Bishop modified stability analysis with reinforcement contributing as additional resistance at the failure surface.',
        '11.4': 'MSE wall internal LRFD checks: tensile rupture (T_max < φ × LTDS × R_c), pullout (T_max < φ × τ × L_e × 2 × α), and connection strength. Reinforcement length L = 0.7H minimum. RSS slopes use similar reinforcement with shorter embedment and more flexible facing. Both require granular select fill (φ ≥ 34°) within the reinforced zone. Electrochemical limits per FHWA GEC-11 Tables 3-3/3-4.',
        '11.5': 'In CSE systems, geosynthetic reinforcement in the LTP carries differential load between column heads by tensile membrane action. Design tension T calculated from vertical equilibrium of the soil arching zone above the geosynthetic. Strain compatibility required: strain in geosynthetic must be consistent with allowable differential settlement. Multiple geosynthetic layers in LTP are common for higher embankments.',
        '11.6': 'Installation: orient primary strength direction perpendicular to wall or parallel to maximum tension; seam/overlap requirements (typically 0.6-1.5 m overlap for embankments; mechanical connections for MSE walls); protect from installation damage (RF_ID = 1.1-3.0 by polymer and fill gradation); do not expose to UV for extended periods before burial. QC: visual inspection, panel tensile testing, and damage assessment.',
        '11.7': 'Primary references: FHWA GEC-11 (FHWA-NHI-10-024, Elias et al. 2009) for MSE walls and RSS; FHWA-HI-95-038 (Holtz et al. 1995) for reinforcement and drainage; AASHTO LRFD Sections 11.10 and 3.11; BS 8006:2010 for reinforced fills; ASTM D4595 (geotextile tensile properties), D6637 (geogrids).',
    },
}


def add_summaries(chapter_key, section_summaries):
    fn = os.path.join('geotech_references', 'gec_13', 'text', f'{chapter_key}.json')
    with open(fn, encoding='utf-8') as f:
        d = json.load(f)

    updated = 0
    for s in d['sections']:
        sid = s['section_id']
        if sid in section_summaries and 'summary' not in s:
            # Rebuild dict with summary after title
            new_s = {}
            for k, v in s.items():
                new_s[k] = v
                if k == 'title':
                    new_s['summary'] = section_summaries[sid]
            s.clear()
            s.update(new_s)
            updated += 1

    with open(fn, 'w', encoding='utf-8') as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    print(f'{chapter_key}: added {updated}/{len(d["sections"])} summaries')


if __name__ == '__main__':
    for chapter_key, section_summaries in SUMMARIES.items():
        add_summaries(chapter_key, section_summaries)
    print('Done.')
